export const subjectsStatistics = [
  {
    id: 1,
    subjectName: 'English Language',
    teacher: ['Walter Vargas'],
    boys: 25,
    girls: 30,
    total: 55,
    boysPassed: 20,
    girlsPassed: 21,
    percentageBoys: 80,
    percentageGirls: 70,
    percentageClass: 74.5,
  },

  {
    id: 2,
    subjectName: 'Mathematics',
    teacher: ['Cora Martin', 'Maria Sherman'],
    boys: 25,
    girls: 30,
    total: 55,
    boysPassed: 22,
    girlsPassed: 25,
    percentageBoys: 88,
    percentageGirls: 83.5,
    percentageClass: 85.5,
  },

  {
    id: 3,
    subjectName: 'Food Science',
    teacher: ['Cora Martin', 'Maria Sherman'],
    boys: 25,
    girls: 30,
    total: 55,
    boysPassed: 10,
    girlsPassed: 15,
    percentageBoys: 40,
    percentageGirls: 50,
    percentageClass: 63.6,
  },

  {
    id: 4,
    subjectName: 'Economics',
    teacher: ['Cora Martin', 'Maria Sherman'],
    boys: 25,
    girls: 30,
    total: 55,
    boysPassed: 22,
    girlsPassed: 29,
    percentageBoys: 88,
    percentageGirls: 96.7,
    percentageClass: 92.7,
  },

  {
    id: 5,
    subjectName: 'History',
    teacher: ['Emilie Todd'],
    boys: 25,
    girls: 30,
    total: 55,
    boysPassed: 10,
    girlsPassed: 15,
    percentageBoys: 40,
    percentageGirls: 50,
    percentageClass: 63.6,
  },

  {
    id: 6,
    subjectName: 'Geography',
    teacher: ['Ralph Klein', 'Jeremy Nash'],
    boys: 25,
    girls: 30,
    total: 55,
    boysPassed: 22,
    girlsPassed: 29,
    percentageBoys: 88,
    percentageGirls: 96.7,
    percentageClass: 92.7,
  },
]
